#!/bin/bash
#Check for dependencies
dependencies='sed openssl xargs zenity find'
for dep in $dependencies; do
	which $dep 1>/dev/null
	if [ ! $? -eq 0 ]; then
		echo "Error: $dep is required but not installed. Please install it"
		exit 1
	fi
done


where="${HOME}/.environments-enc"
if [[ ! -d ${where} ]]; then
	echo "Environment encoded directory does not exists. Creating it."
	mkdir ${where}
fi

files=$( find "${where}" -name "*.aes256ecb" -printf "%f\n" |sed "s/\.aes256ecb//g" )

if [[ "$1" == "--help" ]]; then
	info=$(cat <<EOINFO
	How to use it:
	    --help
			this
	    --new
			Creates a new environment
	    --edit
			Edit the content of an environment
EOINFO
)
	zenity --info --text="$info" --title="Environment switcher"
	exit 0
fi

if [[ "$1" == "--new" ]]; then
	newAccount=$(zenity --entry --text="One-word identification (no spaces)")
	content=$(zenity --text-info --editable)
	password=$(zenity --password)
	echo -n "$content" | openssl enc -e -aes-256-ecb -pbkdf2 -out "${where}/${newAccount}.aes256ecb" --pass "pass:${password}"
	exit 0
fi


if [[ "$1" == "--edit" ]]; then
	cuenta=$(zenity --list --column="Account" $files)
	password=$(zenity --password)
	content=$(openssl enc -d -aes-256-ecb --pass="pass:${password}" -pbkdf2 -in ${where}/${cuenta}.aes256ecb )
	if [ ! $? -eq 0 ]; then
		zenity --error --text="Wrong password"
		exit 1
	fi
	newContent=$(echo "$content" | zenity --text-info --editable)
	echo -n "$newContent" | openssl enc -e -aes-256-ecb -pbkdf2 -out "${where}/${cuenta}.aes256ecb" --pass="pass:${password}"
	exit 0
fi



cuenta=$(zenity --list --column="Account" $files)
if [[ "${cuenta}" != "" ]]; then
	password=$(zenity --password)
	INIT=$(openssl enc -d -aes-256-ecb -pbkdf2 -in ${where}/${cuenta}.aes256ecb --pass "pass:${password}")
	if [[ "$?" == "0" ]]; then
		INIT=$(echo $INIT | \
			sed -E "s/$/;/g"| \
			xargs | \
			sed -E "s/^/source ~\/.bashrc;export NAMESPACE=${cuenta};/g;s/$/bash/g" \
		)
		bash -c "$INIT"
	else
		zenity --error --text="Wrong password"
	fi

fi

